name: Sync Nuxt Docs

on:
  # schedule:
  #   - cron: "0 2 * * *" # 每天 UTC 时间 2 点（即北京时间早上 10 点）执行
  workflow_dispatch: # 允许手动触发

jobs:
  sync_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: raw
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Download Nuxt Docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "${{ secrets.EMAIL }}}"
          rm -rf docs
          git clone --depth 1 https://github.com/nuxt/nuxt.git

      - name: Commit and Push
        run: |
          cp -r nuxt/docs ./ 
          # 先临时删除 rm -rf nuxt 
          git add docs 
          if [ -n "$(git status --porcelain docs)" ]; then 
            git commit -m "Synchronize Nuxt docs" 
            git push --force 
          fi

      # - name: Commit
      #   run: |
      #     cp -r nuxt/docs ./
      #     # 先临时删除
      #     rm -rf nuxt
      #     git add docs
      #     git commit -m "Synchronize Nuxt docs"
      #     git push --force

      # - name: Merge or create PR
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git checkout -- doc
      #     git merge raw --no-edit || (git merge --abort && echo "Merge conflict, creating PR" && gh pr create --base docs --head raw --title "Merge Nuxt docs" --body "Manual merge required due to conflicts." --repo ${{ github.repository }})
